create user 'springuser'@'%' identified by 'ThePassword';
GRANT ALL PRIVILEGES ON {prod}.* TO 'springuser'@'%';
FLUSH PRIVILEGES;

/* Setting up PROD DB */
create database prod;
use prod;

create table firestation(
ID int   PRIMARY KEY AUTO_INCREMENT,
STATION_NUMBER int NOT NULL,
ADDRESS VARCHAR(250) NOT NULL);

create table person(
ID int   PRIMARY KEY AUTO_INCREMENT,
FIRST_NAME VARCHAR(250) NOT NULL,
LAST_NAME VARCHAR(250) NOT NULL,
ADDRESS VARCHAR(250) NOT NULL,
CITY VARCHAR(250) NOT NULL,
ZIP int NOT NULL,
PHONE VARCHAR(250) NOT NULL,
EMAIL VARCHAR(250) NOT NULL);

create table medicalrecords(
ID int  PRIMARY KEY AUTO_INCREMENT,
FIRST_NAME VARCHAR(250) NOT NULL,
LAST_NAME VARCHAR(250) NOT NULL,
BIRTHDATE DATE NOT NULL,
MEDICATIONS VARCHAR(250) ,
ALLERGIES VARCHAR(250));
 
commit;

/* Setting up TEST  DB */
create database test;
use test;

create table firestation(
STATION_NUMBER int PRIMARY KEY AUTO_INCREMENT,
ADDRESS VARCHAR(250) NOT NULL);

create table person(
ID VARCHAR(250) NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR(250) NOT NULL,
LAST_NAME VARCHAR(250) NOT NULL,
ADDRESS VARCHAR(250) NOT NULL,
CITY VARCHAR(250) NOT NULL,
ZIP int NOT NULL,
PHONE VARCHAR(250) NOT NULL,
EMAIL VARCHAR(250) NOT NULL);

create table medicalrecords(
ID int  PRIMARY KEY AUTO_INCREMENT,
FIRST_NAME VARCHAR(250) NOT NULL,
LAST_NAME VARCHAR(250) NOT NULL,
BIRTHDATE VARCHAR(10)  NOT NULL,
MEDICATIONS VARCHAR(250) ,
ALLERGIES VARCHAR(250));
 
commit;